name: Deploy to AWS S3

on:
  push:
    branches:
      - xxxxx

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
        working-directory: ./client
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./client

      - name: Build Web App
        run: flutter build web --web-renderer html --release
        working-directory: ./client

      - name: Modify Index HTML
        run: |
          # Navigate to the directory containing the index.html file
          cd build/web

          # Replace <base href="/"> with <base href="./">
          sed -i 's/<base href="\/">/<base href=".\/">/' index.html
        working-directory: ./client

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ vars.DEPLOYMENT_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2" # optional: defaults to us-east-1
          SOURCE_DIR: "./client/build/web"
          DEST_DIR: "deployment/dev/"
