name: Deploy to AWS S3
on:
  push:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Terraform Init
        id: init
        run: |
          cd ./terraform
          terraform init -no-color -upgrade
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Apply
        run: |
          cd ./terraform
          terraform apply -auto-approve -no-color -var="environment=${GITHUB_REF##*/}" | tee output.txt
          BUCKET_NAME=$(cat output.txt | grep -oP '(?<=bucket = ).*')
          echo "DEPLOYMENT_BUCKET=$BUCKET_NAME" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - name: Install Dependencies
        run: flutter pub get
      - name: Update dotenv file
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          # Navigate to the assets directory
          cd assets
          # Replace REPLACE_ME with the actual API_URL value in the dotenv file
          echo "API_URL=$API_URL" >> dotenv
      - name: Build Web App
        run: flutter build web --web-renderer html --release
      - name: Modify Index HTML
        run: |
          # Navigate to the directory containing the index.html file
          cd build/web
          # Replace <base href="/"> with <base href="./">
          sed -i 's/<base href="\/">/<base href=".\/">/' index.html
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ env.DEPLOYMENT_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: ./build/web
          DEST_DIR: deployment
